name-template: 'Example title - v0.9.68b0'
tag-template: 'v0.9.68b0'
exclude-labels:
  - 'skip-changelog'
categories:
  - title: 'New Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: 'Translation'
    collapse-after: 2
    labels:
      - 'translation'
  - title: 'Dependencies'
    collapse-after: 2
    labels:
      - 'dependency'
  - title: 'Code quality and maintenance'
    labels:
      - 'maintenance'
      - 'code quality'

  - title: 'Development environment and tools'
    label: 'dev tools'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

template: |
  [![Downloads for this release](https://img.shields.io/github/downloads/$OWNER/$REPOSITORY/v0.9.68b0/total.svg)]
  (https://github.com/$OWNER/$REPOSITORY/releases/v0.9.68b0)


  <!--
  ### Checklist for release
  - Download translations PR from Lokalise
  - Run ruff linter
  - Run make bump - select proper variant in Makefile
  - Review the draft below and update if needed
  - If you are making a pre-release then check the pre-release box below
  -->

  ## Notable changes

  <!-- Write-up of most important news -->

  ## Changes

  $CHANGES

autolabeler:
  - label: 'maintenance'
    files:
      - '*.md'

  - label: 'dev tools'
    files:
      - '.github/*'
      - '.devcontainer.json'
      - 'links.sh'
      - 'Makefile'
      - 'setup.cfg'
      - 'requirements*.txt'
      - '.gitignore'
      - '.pre-commit-config.yaml'
      - '.pylintrc'
      - '*.toml'
  - label: 'bugfix'
    title:
      - '/fix/i'
  - label: 'code quality'
    title:
      - 'lint'
  - label: 'translation'
    title:
      - 'Lokalise:'
    files:
      - '**/translations/*.json'
