name-template: "Example title - v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"
exclude-labels:
  - "skip-changelog"
categories:
  - title: "New Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "Translation"
    collapse-after: 2
    labels:
      - "translation"
  - title: "Dependencies"
    collapse-after: 2
    labels:
      - "dependency"
  - title: "Code quality and maintenance"
    labels:
      - "maintenance"
      - "code quality"

  - title: "Development environment and tools"
    label: "dev tools"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

template: |
  [![Downloads for this release](https://img.shields.io/github/downloads/nordicopen/easee_hass/v$RESOLVED_VERSION/total.svg)](https://github.com/nordicopen/easee_hass/releases/v$RESOLVED_VERSION)

  <!--
  ### Checklist for release
  - Download translations PR from Lokalise
  - Run ruff linter
  - Run make bump - select proper variant in Makefile
  - Review the draft below and update if needed
  -->

  ## Changes

  $CHANGES

autolabeler:
  - label: "maintenance"
    files:
      - "*.md"

  - label: "dev tools"
    files:
      - ".github/*"
      - ".devcontainer.json"
      - "links.sh"
      - "Makefile"
      - "setup.cfg"
      - "requirements*.txt"
      - ".gitignore"
      - ".pre-commit-config.yaml"
      - ".ruff.toml"
      - ".pylintrc"
  - label: "bugfix"
    title:
      - "/fix/i"
  - label: "code quality"
    title:
      - "lint"
  - label: "translation"
    title:
      - "Lokalise:"
    files:
      - "**/translations/*.json"
