[bumpver]
current_version = "0.9.67"
version_pattern = "MAJOR.MINOR.PATCH[PYTAGNUM]"
commit_message = "Bump version from {old_version} to {new_version}"
commit = false

[bumpver.file_patterns]
"pyproject.toml" = ['current_version = "{version}"']

"**/const.py" = ['VERSION = "{version}"']

"**/manifest.json" = ['"version": "{version}"']
