start:
  description: Starts charger
  fields:
    charger_id:
      description: "The charger id"
      example: "EH123456"

stop:
  description: Stop charger
  fields:
    charger_id:
      description: "The charger id"
      example: "EH123456"

pause:
  description: Pause charger
  fields:
    charger_id:
      description: "The charger id"
      example: "EH123456"

resume:
  description: Resume charger
  fields:
    charger_id:
      description: "The charger id"
      example: "EH123456"

toggle:
  description: Toggle charger
  fields:
    charger_id:
      description: "The charger id"
      example: "EH123456"

set_basic_charge_plan:
  description: Set basic charge plan
  fields:
    charger_id:
      description: "The charger id"
      example: "EH123456"
    start_datetime:
      description: "Plan start time"
      example: "2020-07-28T19:51"
    stop_datetime:
      description: "Plan stop time"
      example: "2020-07-28T19:51"
    repeat:
      description: "Repeat plan"
      example: True

delete_basic_charge_plan:
  description: Delete basic charge plan
  fields:
    charger_id:
      description: "The charger id"
      example: "EH123456"

override_schedule:
  description: Override charger schedule and start charging
  fields:
    charger_id:
      description: "The charger id"
      example: "EH123456"

smart_charging:
  description: Enable smart charging
  fields:
    charger_id:
      description: "The charger id"
      example: "EH123456"

reboot:
  description: Reboot charger
  fields:
    charger_id:
      description: "The charger id"
      example: "EH123456"

update_firmware:
  description: Update charger firmware
  fields:
    charger_id:
      description: "The charger id"
      example: "EH123456"

set_circuit_dynamic_current:
  description: Set circuit dynamic current
  fields:
    circuit_id:
      description: "The circuit id"
      example: "11000"
    currentP1:
      description: "Phase 1 current"
      example: 10
    currentP2:
      description: "Phase 2 current (Optional)"
      example: 10
    currentP3:
      description: "Phase 3 current (Optional)"
      example: 10

set_circuit_max_current:
  description: Set circuit max current
  fields:
    circuit_id:
      description: "The circuit id"
      example: "11000"
    currentP1:
      description: "Phase 1 current"
      example: 10
    currentP2:
      description: "Phase 2 current (Optional)"
      example: 10
    currentP3:
      description: "Phase 3 current (Optional)"
      example: 10

set_charger_dynamic_current:
  description: Set circuit dynamic current
  fields:
    charger_id:
      description: "The charger id"
      example: "EH123456"
    currentP1:
      description: "Phase 1 current"
      example: 10
    currentP2:
      description: "Phase 2 current (Optional)"
      example: 10
    currentP3:
      description: "Phase 3 current (Optional)"
      example: 10

set_charger_max_current:
  description: Set circuit max current
  fields:
    charger_id:
      description: "The charger id"
      example: "EH123456"
    currentP1:
      description: "Phase 1 current"
      example: 10
    currentP2:
      description: "Phase 2 current (Optional)"
      example: 10
    currentP3:
      description: "Phase 3 current (Optional)"
      example: 10
